### ISSUE TITLE
Feature: Adding prop for search input placeholder

### ISSUE THREAD

**Issue by talisraeli** [MrBartusek/gif-picker-react#18]
Adding an option to change the default "Search Tenor" placeholder in the search input for a custom one.

**Comment by MrBartusek** [comment]
This is the way we follow the [atribution guidelines](https://developers.google.com/tenor/guides/attribution) not sure if giving end-user ability to change that is a good idea

**Comment by jaxomlotus** [comment]
I would also like to be able to pass in search terms in advance of loading the default states. It's easy enough to follow the attribution guidelines with some of the powered by logos they provide.
