### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by shu-vro** [MrBartusek/gif-picker-react#24]
Imagine what happens if I provide a wrong api key?
There should be a onError handler so that I can explicitly see if my api key is wrong? like I refreshed my tenor api key.

**Comment by MrBartusek** [comment]
Hey! In case of any internal errors including bugs, tenor outages or invalid/restricted api key an error is always printed to console. There is also error boundary so, picker just doesn't render on error. I dont see the need for onError property. Realistically, it should never be called and don't have any use.

**Comment by shu-vro** [comment]
Well, the error shows in the console but in case I mistakenly refresh my API key, or my account gets suspended or something like that (the worst-case scenario), this error could affect the build version of my web app. In that case, I want to make an alert to the end user that the tenor API key has been changed so that they address that issue to me.

**Comment by MrBartusek** [comment]
Hey! In that case, you should use [sentry](https://sentry.io/welcome/) or any other similar monitoring software. The soluution that you are talking about is not-standard and won't be implemented.
