### ISSUE TITLE
Gif picker react contentFilter  is not working 

### ISSUE THREAD

**Issue by Ramkumar-r7** [MrBartusek/gif-picker-react#26]
So I was using gif-picker-react:'1.3.2  and this is how I was using the gif picker  in my code ,I was trying to pass contentFilter as OFF 
![image](https://github.com/MrBartusek/gif-picker-react/assets/115092135/c70f27ca-51a8-4ab4-a385-2190e31d58c6)
![image (1)](https://github.com/MrBartusek/gif-picker-react/assets/115092135/7f553355-7d5b-45d3-b682-f374276f6024)
but still i am getting those contents

**Comment by Ramkumar-r7** [comment]
> So I was using gif-picker-react:'1.3.2 and this is how I was using the gif picker in my code ,I was trying to pass contentFilter as OFF ![image](https://private-user-images.githubusercontent.com/115092135/303915882-c70f27ca-51a8-4ab4-a385-2190e31d58c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTIzMzEsIm5iZiI6MTcwNzY1MjAzMSwicGF0aCI6Ii8xMTUwOTIxMzUvMzAzOTE1ODgyLWM3MGYyN2NhLTUxYTgtNGFiNC1hMzg1LTIxOTBlMzFkNThjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxMTQ3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjllZTY3OTE0NDA1Y2U2OWNjY2I4YTQ1OGE4ZDdhNDdhYWRhNTQ2Njk3MjAyMzZlNGI1Njk2Y2ZlMzkxOWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8gJpvCK4V4TqY5P3Y4Kt7-phVa9xSlWeSOISgQvv_UY) ![image (1)](https://private-user-images.githubusercontent.com/115092135/303915903-7f553355-7d5b-45d3-b682-f374276f6024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTIzMzEsIm5iZiI6MTcwNzY1MjAzMSwicGF0aCI6Ii8xMTUwOTIxMzUvMzAzOTE1OTAzLTdmNTUzMzU1LTdkNWItNDVkMy1iNjgyLWYzNzQyNzZmNjAyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxMTQ3MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmY2ZDY1MGYwMzg5YjE2NWNhMWZlZWYwMDQ4MDU1MjcyMWJmNzViZjFhMjRkYWE2MjQyNGJjZWZiMmRlMTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2zO_zrY8mVPnvW-tMfju-mJxatD1JHXx3KhW4pGyTEU) but still i am getting those contents

In the above I have passed HIGH but I have tried OFF also its not reflecting

**Comment by MrBartusek** [comment]
Hey, I've just checked that and it seems to be working as expected. Passing `contentFilter={ContentFilter.HIGH}` produces more friendly search results and category preview images.

For example one of today's featured categories `kissing` shows vastly different results depending on this prop:

With `ContentFilter.OFF` (default) it shows more *verbose* results:

![image](https://github.com/MrBartusek/gif-picker-react/assets/23432278/5ae442be-f12d-4e8c-9342-2db1f64826eb)

And `ContentFilter.HIGH` shows filtered results: 

![image](https://github.com/MrBartusek/gif-picker-react/assets/23432278/cd4d8c8e-f7cf-48cb-a874-757b3ca29219)


> In the above I have passed HIGH but I have tried OFF and it is not reflecting and I have the API key as well

This is expected - `ContentFilter.OFF` is the default
