### ISSUE TITLE
Add disabled property

### ISSUE THREAD

**Issue by ptahchiev** [MrBartusek/gif-picker-react#27]
Hello,

is there a chance to add a `disabled` property to be able to be able to control the disabled state?

Thank you and keep up the good work.

**Comment by MrBartusek** [comment]
Hey, I've trouble understanding your vision for this future. To consider it I need to ask additional questions:

- How would you handle the user experience when the `disabled` prop is passed? How would the picker look like and behave when disabled?
- What would be the use cases of this property? Can you present examples where it would be useful?

**Comment by ptahchiev** [comment]
Sure,
my thought is that if I set the disabled property to true then the button would be clickable and also the panel to select a gif would not open.
My use case is the following. I am implementing a chat where users are able to send gifs. The chat feature is enabled only when the user has paid a monthly subscription. If the user has not paid a monthly subscription the textarea for chatting is disabled (they cannot input text) but I also want to disable the gif picker button so that the gif panel doesn't open when clicked.

**Comment by MrBartusek** [comment]
> my thought is that if I set the disabled property to true then the button would be clickable and also the panel to select a gif would not open.

Then you should disable said button element, not the picker.

**Comment by MrBartusek** [comment]
Closing due inactivity
